// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhq-B5Q9C_smuZUJVW-UwYSdCAtw6SgHc',
    appId: '1:21147790097:web:016fed20c1d508a0847ab0',
    messagingSenderId: '21147790097',
    projectId: 'ekatalog-app',
    authDomain: 'ekatalog-app.firebaseapp.com',
    storageBucket: 'ekatalog-app.firebasestorage.app',
    measurementId: 'G-BRH3842ERG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7LwA8AO-1Ts0tgcU565ahC2EI3W_KAmo',
    appId: '1:21147790097:android:614171d139d23a8c847ab0',
    messagingSenderId: '21147790097',
    projectId: 'ekatalog-app',
    storageBucket: 'ekatalog-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl7FMYjM-xYUBuprB-nsN0Q8DdQ-2MA5E',
    appId: '1:21147790097:ios:59c3d427da618c77847ab0',
    messagingSenderId: '21147790097',
    projectId: 'ekatalog-app',
    storageBucket: 'ekatalog-app.firebasestorage.app',
    iosBundleId: 'com.example.etmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl7FMYjM-xYUBuprB-nsN0Q8DdQ-2MA5E',
    appId: '1:21147790097:ios:59c3d427da618c77847ab0',
    messagingSenderId: '21147790097',
    projectId: 'ekatalog-app',
    storageBucket: 'ekatalog-app.firebasestorage.app',
    iosBundleId: 'com.example.etmApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhq-B5Q9C_smuZUJVW-UwYSdCAtw6SgHc',
    appId: '1:21147790097:web:0c01bb3004d08438847ab0',
    messagingSenderId: '21147790097',
    projectId: 'ekatalog-app',
    authDomain: 'ekatalog-app.firebaseapp.com',
    storageBucket: 'ekatalog-app.firebasestorage.app',
    measurementId: 'G-9C1ZYG3RNJ',
  );
}
